language: node_js
node_js:
  - 8.11.4
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
  - cd client/ && yarn install && cd ../
script:
  - yarn lint
  - cd client/ && yarn run build
cache:
  yarn: true
  directories:
    - "node_modules"
    - "client/node_modules"